spring:
  application:
    name: rsupport-api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 300MB
  
  sql:
    init:
      mode: always
      #      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

notice:
  file:
    path: "uploads/notices/"